// app/themes.ts
export type ThemeName = 
  | 'carbon' | 'pixel' | 'neumorphism' | 'cyberpunk' | 'glass' 
  | 'forest' | 'industrial' | 'vaporwave' | 'bauhaus' | 'pipboy' | 'swiss';

export const themes = {
  carbon: {
    bg: "bg-[#f4f4f4] text-[#161616]",
    nav: "border-b border-[#e0e0e0] bg-white/80",
    card: "bg-white border border-[#e0e0e0] shadow-[0_30px_60px_-15px_rgba(0,0,0,0.05)] rounded-sm",
    accent: "text-[#0f62fe]",
    buttonPrimary: "bg-[#0f62fe] text-white hover:bg-[#0353e9] rounded-sm transition-all",
    buttonSecondary: "bg-[#393939] text-white hover:bg-[#4c4c4c] rounded-sm",
    dropzone: "bg-[#f4f4f4] border-[#e0e0e0]",
    font: "font-sans tracking-tight",
    cardText: "text-[#161616]",
  },
  pixel: {
    bg: "bg-[#222] text-[#00ff00] bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]",
    nav: "border-b-4 border-[#00ff00] bg-black",
    card: "bg-black border-4 border-[#00ff00] shadow-[8px_8px_0px_0px_rgba(0,255,0,0.3)]",
    accent: "text-[#00ff00]",
    buttonPrimary: "bg-[#00ff00] text-black font-bold hover:bg-white border-b-4 border-r-4 border-green-900 active:translate-y-1 active:border-0",
    buttonSecondary: "border-2 border-[#00ff00] hover:bg-[#003300] text-[#00ff00]",
    dropzone: "bg-[#111] border-[#00ff00] border-dashed",
    font: "font-mono",
    cardText: "text-[#00ff00]",
  },
  neumorphism: {
    bg: "bg-[#e0e5ec] text-[#44474a]",
    nav: "bg-[#e0e5ec] border-b border-white/20 shadow-[0_2px_10px_rgba(0,0,0,0.1)]",
    card: "bg-[#e0e5ec] shadow-[20px_20px_60px_#bec3c9,-20px_-20px_60px_#ffffff] rounded-[40px]",
    accent: "text-[#4b7cf3]",
    buttonPrimary: "bg-[#e0e5ec] text-[#4b7cf3] shadow-[6px_6px_12px_#bec3c9,-6px_-6px_12px_#ffffff] active:shadow-[inset_4px_4px_8px_#bec3c9,inset_-4px_-4px_8px_#ffffff] rounded-2xl font-bold",
    buttonSecondary: "bg-[#e0e5ec] text-gray-500 shadow-[4px_4px_8px_#bec3c9,-4px_-4px_8px_#ffffff] rounded-2xl",
    dropzone: "bg-[#e0e5ec] shadow-[inset:10px_10px_20px_#bec3c9,inset:-10px_-10px_20px_#ffffff] rounded-[30px]",
    font: "font-sans",
    cardText: "text-[#44474a]",
  },
  cyberpunk: {
    bg: "bg-[#000] text-[#fcee0a] bg-[url('https://www.transparenttextures.com/patterns/asfalt-dark.png')]",
    nav: "border-b-2 border-[#fcee0a] bg-black",
    card: "bg-[#fcee0a] text-black border-l-[10px] border-black shadow-[10px_10px_0px_#00efff]",
    accent: "text-[#00efff]",
    buttonPrimary: "bg-black text-[#fcee0a] font-black uppercase italic hover:bg-[#00efff] hover:text-black transition-all rounded-none border-r-4 border-b-4 border-[#00efff]",
    buttonSecondary: "bg-transparent text-black border-2 border-black font-bold uppercase",
    dropzone: "bg-black/10 border-2 border-black border-dashed",
    font: "font-black tracking-tighter",
    cardText: "text-black",
  },
  glass: {
    bg: "bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500 text-white",
    nav: "bg-white/10 backdrop-blur-md border-b border-white/20",
    card: "bg-white/20 backdrop-blur-xl border border-white/30 shadow-2xl rounded-3xl",
    accent: "text-white",
    buttonPrimary: "bg-white text-purple-600 hover:bg-opacity-90 rounded-2xl font-bold shadow-lg",
    buttonSecondary: "bg-transparent text-white border border-white/50 hover:bg-white/10 rounded-2xl",
    dropzone: "bg-white/5 border-white/20 border-dashed rounded-2xl",
    font: "font-sans",
    cardText: "text-white",
  },
  forest: {
    bg: "bg-[#2D3A3A] text-[#F2E8CF]",
    nav: "bg-[#1A2424] border-b border-[#3D4F4F]",
    card: "bg-[#F2E8CF] text-[#2D3A3A] rounded-xl shadow-lg border border-[#D9CDB0]",
    accent: "text-[#BC6C25]",
    buttonPrimary: "bg-[#606C38] text-white hover:bg-[#283618] rounded-lg shadow-md",
    buttonSecondary: "bg-transparent text-[#2D3A3A] border border-[#2D3A3A]/30 hover:bg-[#2D3A3A]/10 rounded-lg",
    dropzone: "bg-[#2D3A3A]/5 border-2 border-[#2D3A3A]/20 border-dashed rounded-xl",
    font: "font-serif",
    cardText: "text-[#2D3A3A]",
  },
  industrial: {
    bg: "bg-[#002244] text-[#80DAEB] bg-[radial-gradient(#113355_1px,transparent_1px)] [background-size:20px_20px]",
    nav: "bg-[#001122] border-b-2 border-[#80DAEB]",
    card: "bg-[#002244] text-[#80DAEB] border-2 border-[#80DAEB] shadow-[inset_0_0_15px_rgba(128,218,235,0.2)]",
    accent: "text-[#FFFFFF]",
    buttonPrimary: "bg-[#80DAEB] text-[#002244] font-bold hover:bg-white rounded-none border-b-4 border-r-4 border-[#005577]",
    buttonSecondary: "bg-transparent text-[#80DAEB] border border-[#80DAEB] rounded-none hover:bg-[#80DAEB]/10",
    dropzone: "bg-black/20 border border-[#80DAEB] border-dashed",
    font: "font-mono tracking-tight",
    cardText: "text-[#80DAEB]",
  },
  vaporwave: {
    bg: "bg-[#050505] text-[#FF71CE] bg-gradient-to-b from-[#240b36] to-[#050505]",
    nav: "bg-[#FF71CE]/10 backdrop-blur-md border-b-2 border-[#01CDFE]",
    card: "bg-black/60 text-[#FF71CE] border-2 border-[#FF71CE] shadow-[5px_5px_0px_#01CDFE] italic",
    accent: "text-[#B967FF]",
    buttonPrimary: "bg-[#01CDFE] text-black font-black uppercase hover:bg-[#FF71CE] transition-all rounded-none",
    buttonSecondary: "border-2 border-[#B967FF] text-[#B967FF] hover:bg-[#B967FF]/20 rounded-none uppercase",
    dropzone: "bg-[#01CDFE]/5 border border-[#01CDFE] border-dashed",
    font: "font-sans font-black italic tracking-widest",
    cardText: "text-[#FF71CE]",
  },
  bauhaus: {
    bg: "bg-[#F5F5F5] text-[#1A1A1A]",
    nav: "bg-[#1A1A1A] border-b-[6px] border-[#E63946] text-white",
    card: "bg-white border-[4px] border-[#1A1A1A] shadow-[12px_12px_0px_#F1FAEE] rounded-none",
    accent: "text-[#457B9D]",
    buttonPrimary: "bg-[#E63946] text-white font-bold uppercase hover:bg-[#F1C40F] hover:text-black transition-all rounded-none border-b-8 border-r-8 border-[#1A1A1A]",
    buttonSecondary: "bg-[#F1C40F] text-black border-[3px] border-[#1A1A1A] rounded-none",
    dropzone: "bg-[#A8DADC]/10 border-[3px] border-[#1A1A1A] border-dashed",
    font: "font-sans font-black uppercase",
    cardText: "text-[#1A1A1A]",
  },
  pipboy: {
    bg: "bg-[#0A0A0A] text-[#FFB000] bg-[url('https://www.transparenttextures.com/patterns/criss-xcross.png')]",
    nav: "border-b-2 border-[#FFB000]/50 bg-black shadow-[0_0_15px_#FFB00033]",
    card: "bg-[#1A1A1A]/80 text-[#FFB000] border-2 border-[#FFB000] shadow-[0_0_10px_#FFB00066] rounded-sm",
    accent: "text-[#FFCC00]",
    buttonPrimary: "bg-[#FFB000] text-black font-bold hover:bg-[#FFD500] hover:shadow-[0_0_20px_#FFB000] rounded-none uppercase",
    buttonSecondary: "border-2 border-[#FFB000]/50 text-[#FFB000]/50 hover:bg-[#FFB000]/10 rounded-none",
    dropzone: "bg-black/40 border-2 border-[#FFB000] border-dotted",
    font: "font-mono tracking-tighter",
    cardText: "text-[#FFB000]",
  },
  swiss: {
    bg: "bg-[#FFFFFF] text-[#000000]",
    nav: "bg-[#E6192E] text-white border-none",
    card: "bg-[#FFFFFF] text-[#000000] border-t-[20px] border-[#000000] shadow-2xl rounded-none",
    accent: "text-[#E6192E]",
    buttonPrimary: "bg-[#000000] text-white font-bold hover:bg-[#E6192E] transition-all rounded-none",
    buttonSecondary: "bg-[#FFFFFF] text-[#000000] border-4 border-[#000000] font-bold rounded-none",
    dropzone: "bg-[#F2F2F2] border-4 border-[#000000] border-dashed",
    font: "font-sans tracking-tight",
    cardText: "text-[#000000]",
  }
};